name: gzctf-stack

services:
  gzctf:
    image: gztime/gzctf:latest
    container_name: gzctf
    restart: always
    environment:
      - GZCTF_ADMIN_PASSWORD=gzctf_pg_pass_ChangeMe_123!       # đổi sau khi login
      - LC_ALL=vi_VN.UTF-8
      - TZ=Asia/Bangkok
    ports:
      - "8080:8080"
    volumes:
      - ./data/files:/app/files
      - ./appsettings.json:/app/appsettings.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./src/GZCTF/ClientApp/build  # <— FE bạn vừa build
        target: /app/wwwroot
        read_only: true
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - gzctf_net

  db:
    image: postgres:15-alpine
    container_name: gzctf-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gzctf_pg_pass_ChangeMe_123!
      - POSTGRES_DB=gzctf
      - TZ=Asia/Bangkok
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gzctf || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gzctf_net

  cache:
    image: redis:alpine
    container_name: gzctf-cache
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gzctf_net

networks:
  gzctf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24   # đổi nếu đụng mạng hiện có
volumes:
  db-data: